name: foobar-database

channels:
  - defaults
  - conda-forge
  - bioconda
  - conda-forge

dependencies:
  - python>=3.8.5

  # foobar-database dependencies
  - scrapy>=2.3.0
  - spacy>=2.3.2
  - pandas>=1.1.0
  - selenium>=3.141.0
  - python-chromedriver-binary>2.42.0
  - pyyaml>=5.3.1
  - fuzzywuzzy=0.17

  # environment management
  - pip
  - pip:
    - webdriver-manager

  # testing
  - pylint>=2.4.4
  - pytest>=6.0.1
  - pytest-cov=2.10.1

  # sqlite
  - sqlite>=3.33
  - ipython-sql>=0.3.9
  - jupyterlab>=2.2.4
